apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./namespace.yaml
- ../../application/example

namespace: dev

images:
- name: gcr.io/uoo-01/oms/oms-auth
  newTag: 3c4f2c35-develop

patchesJson6902:
- path: overlays/patch-service-nodeport.yaml
  target:
    kind: Service
    name: oms-frontend-service
    version: v1

secretGenerator:
- envs:
  - config/secret-env
  name: secrets-env
  type: Opaque

configMapGenerator:
- envs:
  - config/configmap-env
  name: configmap-env
