apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./namespace.yaml
- ../../application/example

namespace: dev

images:
- name: nginx
  newTag: alpine

patchesJson6902:
- path: overlays/patch-service-nodeport.yaml
  target:
    kind: Service
    name: example-service
    version: v1

patchesStrategicMerge:
- replica-count.yaml

secretGenerator:
- envs:
  - config/secret-env
  name: secrets-env
  type: Opaque

configMapGenerator:
- envs:
  - config/configmap-env
  name: configmap-env
