apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  labels:
    app: example
    tier: frontend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: example
        ports:
        - containerPort: 80
          name: example-port
          protocol: TCP
